# Source: dotnet-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-otl-sample
  labels:
    app.kubernetes.io/name: "python-otl-sample"
    app.kubernetes.io/instance: "python"
    app.kubernetes.io/version: "latest"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "python-otl-sample"
    app.kubernetes.io/instance: "python"
---
# Source: dotnet-template/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-otl-sample
  labels:
    app.kubernetes.io/name: "python-otl-sample"
    app.kubernetes.io/instance: "python"
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "python-otl-sample"
      app.kubernetes.io/instance: "python"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "python-otl-sample"
        app.kubernetes.io/instance: "python"
    spec:
      containers:
        - name: python-otl-sample-container
          securityContext: null
          image: python-otl-sample:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          resources:
            limits:
              cpu: 1100m
              memory: 1280Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: python-otl-sample
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-otl-sample
              port:
                number: 80