# /tmp/otel-collector-config.yaml
receivers:
  opencensus:
    endpoint: "0.0.0.0:55679"
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:55678"
      grpc:
exporters:
    logging:
      loglevel: debug
    jaeger:
      endpoint: jaeger-all-in-one:14250
      insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
processors:
    batch:
service:
    pipelines:
        traces:
            receivers: [otlp, opencensus]
            exporters: [logging, jaeger]
            processors: [batch]
        metrics:
            receivers: [otlp]
            exporters: [logging, prometheus]