# /tmp/otel-collector-config.yaml
receivers:
  opencensus:
    endpoint: "0.0.0.0:55679"
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:55678"
      grpc:
exporters:
    logging:
      loglevel: debug
    jaeger:
      endpoint: jaeger-all-in-one:14250
      insecure: true
    file:
      path: ./filename.json
processors:
    batch:
service:
    pipelines:
        traces:
            receivers: [opencensus,otlp]
            exporters: [logging,jaeger]
            processors: [batch]